### PR TITLE
Update cmb-field-map.php

### PR DESCRIPTION
**Pull request by oaattia**
Solving issue #44

### CODE REVIEW

**Comment by oaattia** [comment]
To fix the referenced issue, i updated the method `setup_admin_scripts` 

just you can add in your `functions.php` the below code 

```php
 // add the plugin's google map api key 
     add_filter('os-pw-google-maps-api-key', function(){
     return 'APIKEY';
});
```

**Note :** head to google map to get api key if you don't have one

**Comment by askz** [comment]
Thanks for the PR. Hope this will be merged ASAP!

**Comment by phh** [comment]
Any news here?

**Comment by phh** [comment]
While we wait for this to get merged in here is a little filter that might help you:

```
add_filter( 'cmb2_render_pw_map', function() {
	wp_deregister_script( 'pw-google-maps-api' );
	wp_register_script( 'pw-google-maps-api', '//maps.googleapis.com/maps/api/js?libraries=places&key=<API-KEY>', null, null );
}, 12 );
```

**Pull request closed without merging**
