### PR TITLE
Add an action after display lat/long for other fields to be hooked in

### PR DESCRIPTION
**Pull request by bradp**
We're using this plugin on a project at WebDevStudios, and would rather not have to build our own fork for more fields inside of this, adding an action after displaying the fields is more than enough to hook in.

Thanks!

### CODE REVIEW

**Comment by bradp** [comment]
Actually, I'm dumb. CMB2 lets us do this without needing an action in the custom field.

**Comment by jtsternberg** [comment]
As an educational example of what @bradp is saying:
```php
function parbs_cmb2_render_after_pw_map() {
	// more fields
}
add_action( 'cmb2_render_pw_map', 'parbs_cmb2_render_after_pw_map', 11, 5 );
```

**Comment by mustardBees** [comment]
Glad you guys got this sorted. Purely out of curiosity... what are you hooking in after the map?

**Comment by bradp** [comment]
Phil, once we get this project wrapped up, we'd love to share what we're doing with it. It's pretty neat!

**Pull request closed without merging**
